CREATE SCHEMA IF NOT EXISTS airflow;
CREATE SCHEMA IF NOT EXISTS naturalization;
CREATE SCHEMA IF NOT EXISTS cnpj;
CREATE SCHEMA IF NOT EXISTS sanctions;
CREATE SCHEMA IF NOT EXISTS contracts;
CREATE SCHEMA IF NOT EXISTS finep;

GRANT ALL PRIVILEGES ON SCHEMA airflow TO osint_admin;
GRANT ALL PRIVILEGES ON SCHEMA naturalization TO osint_admin;
GRANT ALL PRIVILEGES ON SCHEMA cnpj TO osint_admin;
GRANT ALL PRIVILEGES ON SCHEMA sanctions TO osint_admin;
GRANT ALL PRIVILEGES ON SCHEMA contracts TO osint_admin;
GRANT ALL PRIVILEGES ON SCHEMA finep TO osint_admin;
