# Generated by Django 4.2.28 on 2026-02-17 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'db_table': '"cnpj"."cnae"',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_basico', models.CharField(help_text='Base CNPJ number (first 8 digits)', max_length=8, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, help_text='Company legal name', max_length=255, null=True)),
                ('capital_social', models.DecimalField(decimal_places=2, help_text='Registered capital', max_digits=15)),
                ('porte_empresa', models.CharField(choices=[('00', 'Não informado'), ('01', 'Micro empresa'), ('03', 'Empresa de pequeno porte'), ('05', 'Demais')], help_text='Company size code', max_length=2, null=True)),
                ('ente_federativo_responsavel', models.CharField(help_text='Responsible federal entity', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': '"cnpj"."empresa"',
            },
        ),
        migrations.CreateModel(
            name='MotivoSituacaoCadastral',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motivo Situação Cadastral',
                'verbose_name_plural': 'Motivos Situação Cadastral',
                'db_table': '"cnpj"."motivo_situacao_cadastral"',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': '"cnpj"."municipio"',
            },
        ),
        migrations.CreateModel(
            name='NaturezaJuridica',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Natureza Jurídica',
                'verbose_name_plural': 'Naturezas Jurídicas',
                'db_table': '"cnpj"."natureza_juridica"',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': '"cnpj"."pais"',
            },
        ),
        migrations.CreateModel(
            name='QualificacaoSocio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Qualificação Sócio',
                'verbose_name_plural': 'Qualificações Sócios',
                'db_table': '"cnpj"."qualificacao_socio"',
            },
        ),
        migrations.CreateModel(
            name='Simples',
            fields=[
                ('empresa', models.OneToOneField(db_column='cnpj_basico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='simples', serialize=False, to='cnpj.empresa')),
                ('opcao_simples', models.CharField(help_text='Simples Nacional option (S/N)', max_length=1, null=True)),
                ('data_opcao_simples', models.IntegerField(help_text='Simples Nacional option date (YYYYMMDD)', null=True)),
                ('data_exclusao_simples', models.IntegerField(help_text='Simples Nacional exclusion date (YYYYMMDD)', null=True)),
                ('opcao_mei', models.CharField(help_text='MEI option (S/N)', max_length=1, null=True)),
                ('data_opcao_mei', models.IntegerField(help_text='MEI option date (YYYYMMDD)', null=True)),
                ('data_exclusao_mei', models.IntegerField(help_text='MEI exclusion date (YYYYMMDD)', null=True)),
            ],
            options={
                'verbose_name': 'Simples Nacional',
                'verbose_name_plural': 'Simples Nacional',
                'db_table': '"cnpj"."simples"',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='natureza_juridica',
            field=models.ForeignKey(db_column='natureza_juridica', help_text='Legal nature code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.naturezajuridica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='qualificacao_responsavel',
            field=models.ForeignKey(db_column='qualificacao_responsavel', help_text='Responsible person qualification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.qualificacaosocio'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_socio', models.IntegerField(help_text='Partner type identifier', null=True)),
                ('nome_socio_razao_social', models.CharField(help_text='Partner name or company name', max_length=255, null=True)),
                ('cpf_cnpj_socio', models.CharField(help_text='Partner CPF or CNPJ', max_length=14, null=True)),
                ('data_entrada_sociedade', models.IntegerField(help_text='Date joined company (YYYYMMDD)', null=True)),
                ('representante_legal', models.CharField(help_text='Legal representative CPF', max_length=14, null=True)),
                ('nome_do_representante', models.CharField(help_text='Legal representative name', max_length=255, null=True)),
                ('faixa_etaria', models.IntegerField(help_text='Age range code', null=True)),
                ('empresa', models.ForeignKey(db_column='cnpj_basico', on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='cnpj.empresa')),
                ('pais', models.ForeignKey(db_column='pais', help_text='Country code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.pais')),
                ('qualificacao_representante_legal', models.ForeignKey(db_column='qualificacao_representante_legal', help_text='Representative qualification code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes', to='cnpj.qualificacaosocio')),
                ('qualificacao_socio', models.ForeignKey(db_column='qualificacao_socio', help_text='Partner qualification code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.qualificacaosocio')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'db_table': '"cnpj"."socio"',
                'indexes': [models.Index(fields=['empresa'], name='socio_cnpj_ba_b837dc_idx'), models.Index(fields=['cpf_cnpj_socio'], name='socio_cpf_cnp_f911ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_ordem', models.CharField(help_text='Establishment number (digits 9-12 of CNPJ)', max_length=4)),
                ('cnpj_dv', models.CharField(help_text='Check digit (last 2 digits of CNPJ)', max_length=2)),
                ('identificador_matriz_filial', models.IntegerField(choices=[(1, 'Matriz'), (2, 'Filial')], help_text='Headquarters or branch identifier')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Trade name', max_length=255, null=True)),
                ('situacao_cadastral', models.IntegerField(choices=[(1, 'Nula'), (2, 'Ativa'), (3, 'Suspensa'), (4, 'Inapta'), (8, 'Baixada')], help_text='Registration status', null=True)),
                ('data_situacao_cadastral', models.IntegerField(help_text='Status event date (YYYYMMDD)', null=True)),
                ('nome_cidade_exterior', models.CharField(blank=True, help_text='Foreign city name', max_length=255, null=True)),
                ('data_inicio_atividade', models.IntegerField(help_text='Activity start date (YYYYMMDD)', null=True)),
                ('cnae_fiscal_secundaria', models.TextField(blank=True, help_text='Secondary economic activity codes (comma-separated)', null=True)),
                ('tipo_logradouro', models.CharField(help_text='Street type description', max_length=255, null=True)),
                ('logradouro', models.CharField(help_text='Street name', max_length=255, null=True)),
                ('numero', models.CharField(help_text='Street number', max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, help_text='Address complement', max_length=255, null=True)),
                ('bairro', models.CharField(help_text='Neighborhood', max_length=255, null=True)),
                ('cep', models.CharField(help_text='Postal code', max_length=8, null=True)),
                ('uf', models.CharField(help_text='State code', max_length=2, null=True)),
                ('ddd_1', models.CharField(blank=True, help_text='Primary phone area code', max_length=4, null=True)),
                ('telefone_1', models.CharField(blank=True, help_text='Primary phone number', max_length=8, null=True)),
                ('ddd_2', models.CharField(blank=True, help_text='Secondary phone area code', max_length=4, null=True)),
                ('telefone_2', models.CharField(blank=True, help_text='Secondary phone number', max_length=8, null=True)),
                ('ddd_fax', models.CharField(blank=True, help_text='Fax area code', max_length=4, null=True)),
                ('fax', models.CharField(blank=True, help_text='Fax number', max_length=8, null=True)),
                ('correio_eletronico', models.CharField(blank=True, help_text='Email address', max_length=255, null=True)),
                ('situacao_especial', models.CharField(blank=True, help_text='Special situation description', max_length=255, null=True)),
                ('data_situacao_especial', models.IntegerField(blank=True, help_text='Special situation date (YYYYMMDD)', null=True)),
                ('cnae_fiscal_principal', models.ForeignKey(db_column='cnae_fiscal_principal', help_text='Main economic activity code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimentos_principal', to='cnpj.cnae')),
                ('empresa', models.ForeignKey(db_column='cnpj_basico', on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='cnpj.empresa')),
                ('motivo_situacao_cadastral', models.ForeignKey(db_column='motivo_situacao_cadastral', help_text='Status reason code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.motivosituacaocadastral')),
                ('municipio', models.ForeignKey(db_column='municipio', help_text='Municipality code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.municipio')),
                ('pais', models.ForeignKey(db_column='pais', help_text='Country code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.pais')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'db_table': '"cnpj"."estabelecimento"',
                'indexes': [models.Index(fields=['situacao_cadastral'], name='estabelecim_situaca_416148_idx'), models.Index(fields=['uf'], name='estabelecim_uf_d00e76_idx'), models.Index(fields=['municipio'], name='estabelecim_municip_bb7b3e_idx'), models.Index(fields=['cnae_fiscal_principal'], name='estabelecim_cnae_fi_8cd94d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='estabelecimento',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj_ordem', 'cnpj_dv'), name='unique_estabelecimento_cnpj'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['razao_social'], name='empresa_razao_s_30b597_idx'),
        ),
    ]
