#!/usr/bin/env python3
"""
Parse a WIPO IPC/CPC scheme XML file and output SQL INSERT statements for
populating inpi.ipc_subclasse_ref.

The XML is NOT committed to the repository (too large, ~70 MB).
Download the current edition from:
  https://www.wipo.int/classifications/ipc/en/ → "Master files"
or use the CPC-to-IPC mapping published at:
  https://www.cooperativepatentclassification.org/cpcSchemeAndDefinitions

Usage:
    python3 scripts/parse_ipc_xml.py /path/to/ipc_scheme.xml \
        > infrastructure/postgres/migrations/inpi/V2026.03.29.002__seed_inpi_ipc_ref.sql

The generated SQL file IS committed to the repository as the authoritative seed.
Re-run only when a new IPC edition is published and the seed needs updating.
"""

import sys
import xml.etree.ElementTree as ET

NS = "http://www.wipo.int/classifications/ipc/masterfiles"
P = f"{{{NS}}}"


def extract_title(ipc_entry: ET.Element) -> str | None:
    """
    Return the combined title text of an ipcEntry element.

    Each <titlePart><text> is joined with "; " to match the official
    IPC title format (e.g. "PLANTING; SOWING").
    Only the direct text of the first <text> child of each <titlePart>
    is included — nested <entryReference> elements are skipped.
    """
    title_el = ipc_entry.find(f"{P}textBody/{P}title")
    if title_el is None:
        return None

    parts: list[str] = []
    for title_part in title_el.findall(f"{P}titlePart"):
        text_el = title_part.find(f"{P}text")
        if text_el is not None and text_el.text:
            text = text_el.text.strip()
            if text:
                parts.append(text)

    return "; ".join(parts) if parts else None


def escape_sql(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path_to_xml>", file=sys.stderr)
        sys.exit(1)

    xml_path = sys.argv[1]
    print(f"Parsing {xml_path} ...", file=sys.stderr)

    tree = ET.parse(xml_path)
    root = tree.getroot()
    edition = root.get("edition", "unknown")

    rows: list[tuple[str, str, str, str, str]] = []

    for entry in root.iter(f"{P}ipcEntry"):
        if entry.get("kind") != "u":
            continue

        symbol = (entry.get("symbol") or "").strip()
        if len(symbol) != 4:
            # IPC subclasses are always exactly 4 chars (e.g. A01B).
            # CPC may have longer symbols; skip them.
            continue

        title = extract_title(entry)
        if not title:
            continue

        secao = symbol[0]       # e.g. "A"
        classe = symbol[:3]     # e.g. "A01"
        rows.append((symbol, secao, classe, title, edition))

    print(f"Found {len(rows)} subclasses.", file=sys.stderr)

    # --- SQL output ---
    print(f"-- Auto-generated by scripts/parse_ipc_xml.py")
    print(f"-- IPC edition: {edition}")
    print(f"-- Subclasses: {len(rows)}")
    print(f"-- Do not edit manually — re-run the parser to update.")
    print()
    print("INSERT INTO inpi.ipc_subclasse_ref (simbolo, secao, classe, titulo_en, edition)")
    print("VALUES")

    sql_rows = [
        f"    ('{escape_sql(sym)}', '{escape_sql(sec)}', '{escape_sql(cls)}', '{escape_sql(ttl)}', '{escape_sql(ed)}')"
        for sym, sec, cls, ttl, ed in rows
    ]
    print(",\n".join(sql_rows) + ";")


if __name__ == "__main__":
    main()
