-- ============================================================
-- INPI — IPC Subclass Reference Table
--
-- Stores the official IPC subclass-level descriptions (4-char symbols
-- like A01B, F41A) extracted from the WIPO IPC master file XML.
--
-- Populated by:
--   V2026.03.29.002__seed_inpi_ipc_ref.sql  (generated by scripts/parse_ipc_xml.py)
--
-- Join key against mv_patent_search:
--   mv_patent_search.ipc_secao_classe = ipc_subclasse_ref.simbolo
-- ============================================================

CREATE TABLE IF NOT EXISTS inpi.ipc_subclasse_ref (
    simbolo     VARCHAR(4)   PRIMARY KEY,  -- 4-char IPC subclass, e.g. A01B
    secao       CHAR(1)      NOT NULL,     -- Section letter, e.g. A
    classe      VARCHAR(3)   NOT NULL,     -- Class code,   e.g. A01
    titulo_en   TEXT         NOT NULL,     -- English title from WIPO XML
    edition     VARCHAR(10)  NOT NULL      -- IPC edition date, e.g. 20260101
);

COMMENT ON TABLE inpi.ipc_subclasse_ref IS
    'WIPO IPC subclass reference table. '
    'Seeded by V2026.03.29.002 (auto-generated via scripts/parse_ipc_xml.py). '
    'Re-seed when a new IPC edition is published.';

COMMENT ON COLUMN inpi.ipc_subclasse_ref.simbolo IS
    'IPC subclass symbol (4 chars, no spaces). '
    'Matches inpi.mv_patent_search.ipc_secao_classe.';

COMMENT ON COLUMN inpi.ipc_subclasse_ref.edition IS
    'IPC edition year in YYYYMMDD format (from XML root attribute "edition").';

CREATE INDEX IF NOT EXISTS idx_inpi_ipc_ref_secao
    ON inpi.ipc_subclasse_ref (secao);

CREATE INDEX IF NOT EXISTS idx_inpi_ipc_ref_classe
    ON inpi.ipc_subclasse_ref (classe);

GRANT ALL PRIVILEGES ON inpi.ipc_subclasse_ref TO osint_admin;
